### ISSUE TITLE
Whatever I try I wasn't able to make the animations work on any of my browsers

### ISSUE THREAD

**Issue by nmudd037** [animate-css/animate.css#1060] opened 2020-05-12 01:57 UTC
**Describe the bug** A clear and concise description of what the bug is.

I am just starting with the html and css and I am completely novice in the area of web development, so in this situation I might go wrong somewhere but I am just trying to find the solution. I just wanted to include animations like bounce, pulse e.t.c on a basic html page, but whatever I tried to do I couldn't able to create animations on the html page.

**To Reproduce** Steps to reproduce the behavior:

I just used this basic html code:

<!DOCTYPE html>
<html>
<head>
	<title>E1</title>
	<link rel="stylesheet" 
 href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"
  />
</head>
<body>
<h1 class="animate_animated animate_bounce"> Hello!!! </h1>
</body>
</html>

![image](https://user-images.githubusercontent.com/65065118/81630306-3f716500-93d3-11ea-8680-81ac65cb3252.png)

I also tried linking the animate.min.css as an external style sheet instead of CDN option, but both options doesn't seem to work for me (I checked on chrome, firefox and edge). I thought  there was a problem with my pc or browser as a reason the animations might not work,  But, the animations on your site works perfectly in all my browsers and I could see the animation effects. Furthermore, I even wrote a small code for bounce animation in css and it's working fine.

I honestly have no idea where I am going wrong in implementing animate.css.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows X
- Browser [e.g. chrome, safari] chrome, firefox and edge.
- Version [e.g. 22] latest version on all browsers.

**Comment by eltonmesquita** [comment] 2020-05-12 10:41
Hi, the problem is that you're writing `animate_` (with **one** dash only) and not `animate__` (with **two** dashes). The full example is:

```html
<h1 class="animate__animated animate__bounce">Hello!</h1>
```

Please refer to the [documentation](https://animate.style) for guidance.

Sorry, but if you need help with usage, you should seek help on a place like StackOverflow as this is used to report issues and give suggestion for improving the library.

I'm closing this.

**Closed by eltonmesquita** 2020-05-12 10:41 UTC
